version: '3'

tasks:
  render-go-cli:
    desc: render go-cli template to a temporary folder for verification
    preconditions:
      - command -v scaffold
    cmds:
      - rm -rfv ./tmp/${NAME}
      - |
        scaffold \
          --run-hooks=true \
          new \
          --output-dir=./tmp \
          --no-prompt=true \
          --preset=${PRESET} \
          ./templates/go-cli
      - |
        scaffold new \
          --output-dir=./tmp/${NAME} \
          ./templates/global/git-hook
    env:
      NAME:
        sh: echo ${NAME:-go-cli-project}
      PRESET: example

  render-go-worker:
    desc: render go-worker template to a temporary folder for verification
    preconditions:
      - command -v boilerplate
    cmds:
      - |
        boilerplate \
          --template-url ./templates/go-worker \
          --output-folder ./tmp \
          --missing-config-action ignore \
          --non-interactive \
          --var name=${NAME} \
          --var go_version=${GO_VERSION} \
          --var with_kustomize=true
    env:
      NAME:
        sh: echo ${NAME:-go-worker-project}
      GO_VERSION:
        sh: echo ${GO_VERSION:-1.21}

  render-asdf-plugin:
    desc: render asdf-plugin template to a temporary folder for verification
    preconditions:
      - command -v boilerplate
    cmds:
      - |
        boilerplate \
          --template-url ./templates/asdf-plugin \
          --output-folder ./tmp \
          --non-interactive \
          --var target_github_owner=gruntwork-io \
          --var target_github_repo=boilerplate
