version: '3'

tasks:
  render-go-cli:
    desc: render go-cli template to a temporary folder for verification
    preconditions:
      - command -v boilerplate
    cmds:
      - |
        boilerplate \
          --template-url ./go-cli \
          --output-folder ./tmp \
          --missing-config-action ignore \
          --non-interactive \
          --var name=${NAME} \
          --var go_version=${GO_VERSION}
    env:
      NAME:
        sh: echo ${NAME:-go-cli-project}
      GO_VERSION:
        sh: echo ${GO_VERSION:-1.21}

  render-go-worker:
    desc: render go-worker template to a temporary folder for verification
    preconditions:
      - command -v boilerplate
    cmds:
      - |
        boilerplate \
          --template-url ./go-worker \
          --output-folder ./tmp \
          --missing-config-action ignore \
          --non-interactive \
          --var name=${NAME} \
          --var go_version=${GO_VERSION}
    env:
      NAME:
        sh: echo ${NAME:-go-worker-project}
      GO_VERSION:
        sh: echo ${GO_VERSION:-1.21}

  render-asdf-plugin:
    desc: render asdf-plugin template to a temporary folder for verification
    preconditions:
      - command -v boilerplate
    cmds:
      - |
        boilerplate \
          --template-url ./asdf-plugin \
          --output-folder ./tmp \
          --non-interactive \
          --var target_github_owner=hpcsc \
          --var target_github_repo=aws-profile
