version: '3'

tasks:
  render-go-cli:
    desc: render go-cli template to a temporary folder for verification
    preconditions:
      - command -v scaffold
    cmds:
      - rm -rfv ./tmp/${NAME}
      - |
        scaffold \
          --run-hooks=true \
          new \
          --output-dir=./tmp \
          --no-prompt=true \
          --preset=${PRESET} \
          ./templates/go-cli
      - |
        scaffold new \
          --output-dir=./tmp/${NAME} \
          ./templates/global/git-hook
    env:
      NAME:
        sh: echo ${NAME:-go-cli-project}
      PRESET: example

  render-go-worker:
    desc: render go-worker template to a temporary folder for verification
    preconditions:
      - command -v scaffold
    cmds:
      - rm -rfv ./tmp/${NAME}
      - |
        scaffold \
          --run-hooks=true \
          new \
          --output-dir=./tmp \
          --no-prompt=true \
          --preset=${PRESET} \
          ./templates/go-worker
      - |
        scaffold new \
          --output-dir=./tmp/${NAME} \
          ./templates/global/git-hook
      - |
        scaffold new \
          --output-dir=./tmp/${NAME} \
          --no-prompt=true \
          --preset=${PRESET} \
          ./templates/global/kustomize
    env:
      NAME:
        sh: echo ${NAME:-go-worker-project}
      PRESET: example

  render-chi-api:
    desc: render chi-api template to a temporary folder for verification
    preconditions:
      - command -v scaffold
    cmds:
      - rm -rfv ./tmp/${NAME}
      - |
        scaffold \
          --run-hooks=true \
          new \
          --output-dir=./tmp \
          --no-prompt=true \
          --preset=${PRESET} \
          ./templates/chi-api
      - |
        scaffold new \
          --output-dir=./tmp/${NAME} \
          ./templates/global/git-hook
      - |
        scaffold new \
          --output-dir=./tmp/${NAME} \
          --no-prompt=true \
          --preset=example \
          ./templates/global/kustomize
    env:
      NAME:
        sh: echo ${NAME:-chi-api-project}
      PRESET: example

  render-asdf-plugin:
    desc: render asdf-plugin template to a temporary folder for verification
    preconditions:
      - command -v boilerplate
    cmds:
      - |
        boilerplate \
          --template-url ./templates/asdf-plugin \
          --output-folder ./tmp \
          --non-interactive \
          --var target_github_owner=gruntwork-io \
          --var target_github_repo=boilerplate
