version: '3'

tasks:
  install-cookiecutter:
    cmds:
      - python3 -m pip install --user cookiecutter
    status:
      - command -v cookiecutter

  render-go-cli:
    desc: render to a temporary folder for verification
    deps:
      - install-cookiecutter
    cmds:
      - rm -rfv ./tmp && mkdir -v ./tmp
      - cookiecutter -v -f go-cli name=${NAME} go_version=${GO_VERSION} --no-input -o ./tmp
    env:
      NAME:
        sh: echo ${NAME:-my-project}
      GO_VERSION:
        sh: echo ${GO_VERSION:-1.21}
