x-db-config: &x-db-config
  DB_NAME: ${DB_NAME}
  DB_USERNAME: ${DB_USERNAME}
  DB_PASSWORD: ${DB_PASSWORD}
  DB_HOST_PORT: 5432
  DB_HOST: db

services:
  api:
    depends_on:
      migrate:
        condition: service_completed_successfully
    build:
      dockerfile: Dockerfile.api
      args:
        VERSION: main
    volumes:
      - ./local/api:/var/run
    ports:
      - "3333:3333"
    environment:
      <<: *x-db-config

  catchup:
    depends_on:
      migrate:
        condition: service_completed_successfully
    build:
      dockerfile: Dockerfile.catchup
    environment:
      <<: *x-db-config
