[tools]
go = "{{ .Scaffold.GoVersion }}"
"aqua:go-task/task" = "3.42.1"
"aqua:gotestyourself/gotestsum" = "1.12.1"
"aqua:koalaman/shellcheck" = "0.10.0"
"aqua:golang-migrate/migrate" = "4.18.2"
"go:golang.org/x/vuln/cmd/govulncheck" = "1.1.4"
