apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{.Scaffold.Name}}
  labels:
    app.kubernetes.io/name: {{.Scaffold.Name}}
    app.kubernetes.io/component: server
    app.kubernetes.io/part-of: {{.Scaffold.Name}}
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: {{.Scaffold.Name}}
  template:
    metadata:
      name: {{.Scaffold.Name}}
      labels:
        app.kubernetes.io/name: {{.Scaffold.Name}}
        app.kubernetes.io/component: server
        app.kubernetes.io/part-of: {{.Scaffold.Name}}
    spec:
      containers:
        - name: nginx
          image: nginx:stable
          ports:
            - name: http
              containerPort: 80
          volumeMounts:
            - name: html
              mountPath: /usr/share/nginx/html
      volumes:
        - name: html
          configMap:
            name: html
