apiVersion: v1
kind: Namespace
metadata:
  name: {{.Scaffold.Name}}
  labels:
    app.kubernetes.io/name: {{.Scaffold.Name}}
    app.kubernetes.io/component: server
    app.kubernetes.io/part-of: {{.Scaffold.Name}}
