apiVersion: v1
kind: Service
metadata:
  name: {{.Scaffold.Name}}
  labels:
    app.kubernetes.io/name: {{.Scaffold.Name}}
    app.kubernetes.io/component: server
    app.kubernetes.io/part-of: {{.Scaffold.Name}}
spec:
  type: NodePort
  ports:
    - name: http
      port: 80
      targetPort: 80
      nodePort: 30222
  selector:
    app.kubernetes.io/name: {{.Scaffold.Name}}
