version: '3'

includes:
  release: Taskfile.release.yml
  test: Taskfile.test.yml

tasks:
  run:
    cmds:
      - go run ./cmd/{{.ProjectKebab}}

  build:
    cmds:
      - mkdir -p ./bin
      - go build --ldflags "-extldflags -static -X 'main.Version=${VERSION}'" -o ./bin/{{.ProjectKebab}} ./cmd/{{.ProjectKebab}}
    env:
      CGO_ENABLED: '0'
      VERSION: ${VERSION:-main}

  hook:setup:
    cmds:
      - git config core.hooksPath ./hooks

  hook:validate-go-changes:
    cmds:
      - task: test:unit
      - task: test:e2e
