#!/bin/bash

set -euo pipefail

cd {{ .ProjectKebab }}

aqua init
aqua generate -i \
    standard,gotestyourself/gotestsum \
    standard,go-task/task \
    standard,koalaman/shellcheck \
    standard,golang/vuln/govulncheck
aqua install
