#!/bin/bash

set -euo pipefail

cd {{ .ProjectKebab }}

go get github.com/fatih/color \
        github.com/mattn/go-isatty \
        github.com/rogpeppe/go-internal \
        github.com/stretchr/testify \
        github.com/urfave/cli/v3

go mod tidy
gofmt -w .

mise use --pin \
    -p . \
    aqua:gotestyourself/gotestsum \
    aqua:go-task/task \
    aqua:koalaman/shellcheck \
    aqua:goreleaser/goreleaser \
    aqua:bats-core/bats-core \
    go:golang.org/x/vuln/cmd/govulncheck

git init
git submodule add https://github.com/bats-core/bats-support.git e2e/support/bats-support
git submodule add https://github.com/bats-core/bats-assert.git e2e/support/bats-assert
