version: '3'

output: prefixed

includes:
  release: Taskfile.release.yml
  test: Taskfile.test.yml

tasks:
  run:
    cmds:
      - go run ./cmd/{{cookiecutter.name}}

  build:
    cmds:
      - mkdir -p ./bin
      - go build --ldflags "-extldflags -static -X 'main.Version=${VERSION}'" -o ./bin/{{cookiecutter.name}} ./cmd/{{cookiecutter.name}}
    env:
      CGO_ENABLED: '0'
      VERSION: ${VERSION:-main}

  setup-git-hooks:
    cmds:
      - git config core.hooksPath ./hooks
