#!/bin/bash

set -euo pipefail

source ./scripts/libs/git-hook-prepush.sh

remote=${1}
fail_if_pushing_to_main "${remote}"

SKIP_PREPUSH_HOOK=${SKIP_PREPUSH_HOOK:-false}
if [ "${SKIP_PREPUSH_HOOK}" = "true" ]; then
    echo_green "skipped prepush hook"
    exit 0
fi

while read local_ref local_sha remote_ref remote_sha
do
  validate "${local_ref}" "${local_sha}" "${remote_ref}" "${remote_sha}"
done
