name: CI

on:
  push: {}

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Install Task
      uses: arduino/setup-task@v2
      with:
        version: 3.x
        repo-token: {{ `${{ secrets.GITHUB_TOKEN }}` }}

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version-file: 'go.mod'

    - name: Run shellcheck
      run: task test:shellcheck

    - name: Build
      run: task build

    - name: Run Unit Test
      run: task test:unit

    - name: Run vulnerabilities check
      run: task test:vulnerabilities
