name: On Demand Build

on:
  workflow_dispatch:
    inputs:
      git_ref:
        description: Git ref to build
        required: true
        default: main

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: {{ `${{ inputs.git_ref }}` }}

      - name: Install Task
        uses: arduino/setup-task@v2
        with:
          version: 3.x
          repo-token: {{ `${{ secrets.GITHUB_TOKEN }}` }}

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: 'go.mod'

      - name: Install GoReleaser
        uses: goreleaser/goreleaser-action@v5
        with:
          install-only: true

      - name: Run release local
        run: task release:local

      - uses: actions/upload-artifact@v3
        with:
          name: darwin-amd64
          path: dist/darwin-amd64.tar.gz

      - uses: actions/upload-artifact@v3
        with:
          name: darwin-arm64
          path: dist/darwin-arm64.tar.gz

      - uses: actions/upload-artifact@v3
        with:
          name: linux-amd64
          path: dist/linux-amd64.tar.gz

      - uses: actions/upload-artifact@v3
        with:
          name: linux-arm64
          path: dist/linux-arm64.tar.gz

      - uses: actions/upload-artifact@v3
        with:
          name: linux-i386
          path: dist/linux-i386.tar.gz
