#!/bin/bash

set -euo pipefail

cd {{ .ProjectKebab }}

go get github.com/caarlos0/env/v6 \
        github.com/go-chi/chi/v5 \
        github.com/gookit/validate \
        github.com/stretchr/testify \
        github.com/unrolled/render
go mod tidy

aqua init
aqua generate -i \
    standard,gotestyourself/gotestsum \
    standard,go-task/task \
    standard,koalaman/shellcheck \
    standard,golang/vuln/govulncheck
aqua install
