#!/bin/bash

set -euo pipefail

cd {{ .ProjectKebab }}

go get github.com/caarlos0/env/v6 \
        github.com/go-chi/chi/v5 \
        github.com/gookit/validate \
        github.com/stretchr/testify \
        github.com/unrolled/render
go mod tidy

{{ if .Scaffold.EnableResilientHttp }}
go get github.com/rs/zerolog \
        github.com/failsafe-go/failsafe-go
{{ end }}

mise use --pin \
    -p . \
    aqua:gotestyourself/gotestsum \
    aqua:go-task/task \
    aqua:koalaman/shellcheck \
    go:golang.org/x/vuln/cmd/govulncheck
