#!/bin/bash

set -euo pipefail

cd {{ .ProjectKebab }}

go get github.com/rs/zerolog
go mod tidy

mise use --pin \
    -p . \
    aqua:gotestyourself/gotestsum \
    aqua:go-task/task \
    aqua:koalaman/shellcheck \
    go:golang.org/x/vuln/cmd/govulncheck
