name: CI

on:
  push: {}

jobs:

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Mise install
        uses: jdx/mise-action@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Run shellcheck
        run: task test:shellcheck

      - name: Run Unit Test
        run: task test:unit

      - name: Run Integration Test
        run: task test:integration

      - name: Run vulnerabilities check
        run: task test:vulnerabilities

  build:
    runs-on: ubuntu-latest
    needs:
      - test
    strategy:
      matrix:
        app: [api, catchup]
    steps:
      - uses: actions/checkout@v4

      - name: Install Task
        uses: arduino/setup-task@v2
        with:
          version: 3.x
          repo-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Build
        run: task ${{ matrix.app }}:docker:build
